version: '3.8'  # Versiya raqami

services:
    web:
        container_name: web
        image: nginx:alpine  # Nginx tasviridan foydalanish
        ports:
            - "80:80"  # Xostda 80-portni ichki 80-portga xaritalash
        volumes:
            - ./:/var/www  # Laravel ilovasi katalogini o'rnatish
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfiguratsiyasi
        depends_on:
            - ticket_booking-app  # Nginx PHP-FPM ishga tushishi uchun
        networks:
            - online_store-network  # Maxsus tarmoqga ulanish

    ticket_booking-app:
        container_name: ticket_booking-app
        build: .  # Dockerfile'dan qurish
        depends_on:
            - ticket_db
        volumes:
            - ./:/var/www  # Laravel ilovasi katalogini o'rnatish
        networks:
            - ticket_booking-network  # Maxsus tarmoqga ulanish

    ticket_db:
        container_name: ticket_db
        image: mysql:8  # MySQL tasviridan foydalanish
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ticket_db  # 'laravel' nomli ma'lumotlar bazasini yaratish
            MYSQL_ROOT_PASSWORD: root  # MySQL uchun root parolni belgilash
        volumes:
            - ./ticket_db:/var/lib/mysql  # MySQL uchun ma'lumotlarni saqlash

        networks:
            - online_store-network  # Maxsus tarmoqga ulanish

    ticket_booking-node:
        container_name: ticket_booking-node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - ticket_booking-network
        command: bash -c "npm install && npm run build"

networks:
    online_store-network:  # 'online_store-network' deb nomlangan maxsus tarmoq
        driver: bridge
    ticket_booking-network:  # 'ticket_booking-network' deb nomlangan maxsus tarmoq
        driver: bridge

volumes:
    ticket_db:
