services:
    web:
        container_name: web
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ticket_booking-app
        networks:
            - online_store-network

    ticket_booking-app:
        container_name: ticket_booking-app
        build: .
        depends_on:
            - ticket_db
        volumes:
            - ./:/var/www
        networks:
            - online_store-network  # To'g'ridan to'g'ri tarmoqga ulanish

    ticket_db:
        container_name: ticket_db
        image: mysql:8
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ticket_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./ticket_db:/var/lib/mysql
        networks:
            - online_store-network

    ticket_booking-node:
        container_name: ticket_booking-node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - online_store-network
        command: bash -c "npm install && npm run build"

networks:
    online_store-network:
        driver: bridge

volumes:
    ticket_db:
